# Generated by Django 5.2.6 on 2025-09-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('ic', models.CharField(max_length=20, unique=True)),
                ('dic', models.CharField(blank=True, max_length=20)),
                ('adresa', models.TextField()),
                ('kontaktni_osoba', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('typ_partnera', models.CharField(choices=[('zakaznik', 'Zákazník'), ('dopravce', 'Dopravce')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Preprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencni_cislo', models.CharField(max_length=50, unique=True)),
                ('misto_nakladky', models.TextField()),
                ('datum_cas_nakladky', models.DateTimeField()),
                ('misto_vykladky', models.TextField()),
                ('datum_cas_vykladky', models.DateTimeField()),
                ('popis_zbozi', models.TextField()),
                ('hmotnost_kg', models.IntegerField(default=0)),
                ('cena_pro_zakaznika', models.DecimalField(decimal_places=2, max_digits=10)),
                ('naklad_pro_dopravce', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stav', models.CharField(choices=[('nova', 'Nová'), ('planovana', 'Plánovaná'), ('dokoncena', 'Dokončená'), ('fakturace', 'K fakturaci'), ('uzavrena', 'Uzavřená')], default='nova', max_length=20)),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('dopravce', models.ForeignKey(blank=True, limit_choices_to={'typ_partnera': 'dopravce'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepravy_dopravce', to='logistika.partner')),
                ('zakaznik', models.ForeignKey(limit_choices_to={'typ_partnera': 'zakaznik'}, on_delete=django.db.models.deletion.PROTECT, related_name='prepravy_zakaznik', to='logistika.partner')),
            ],
        ),
    ]
