# Generated by Django 5.2.6 on 2025-09-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprava',
            name='referencni_cislo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
