# Generated by Django 5.2.6 on 2025-09-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0002_alter_preprava_referencni_cislo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('soubor', models.FileField(upload_to='dokumenty/%Y/%m/%d/')),
                ('datum_nahrani', models.DateTimeField(auto_now_add=True)),
                ('preprava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumenty', to='logistika.preprava')),
            ],
        ),
    ]
