# Generated by Django 5.2.6 on 2025-09-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0003_dokument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprava',
            name='stav',
            field=models.CharField(choices=[('nova', 'Nová'), ('planovana', 'Plánovaná'), ('probiha', 'Probíhá'), ('dokoncena', 'Dokončená'), ('fakturace', 'K fakturaci'), ('uzavrena', 'Uzavřená')], default='nova', max_length=20),
        ),
    ]
