# Generated by Django 5.2.6 on 2025-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0004_alter_preprava_stav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprava',
            name='cena_pro_zakaznika',
        ),
        migrations.RemoveField(
            model_name='preprava',
            name='hmotnost_kg',
        ),
        migrations.RemoveField(
            model_name='preprava',
            name='naklad_pro_dopravce',
        ),
        migrations.AddField(
            model_name='preprava',
            name='cena_za_tunu_zakaznik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena za tunu pro zákazníka'),
        ),
        migrations.AddField(
            model_name='preprava',
            name='finalni_hmotnost_nakladka_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Finální hmotnost nákladka (kg)'),
        ),
        migrations.AddField(
            model_name='preprava',
            name='finalni_hmotnost_vykladka_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Finální hmotnost vykládka (kg)'),
        ),
        migrations.AddField(
            model_name='preprava',
            name='naklad_za_tunu_dopravce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Náklad za tunu pro dopravce'),
        ),
        migrations.AddField(
            model_name='preprava',
            name='odhadovana_hmotnost_kg',
            field=models.IntegerField(default=0, verbose_name='Odhadovaná hmotnost (kg)'),
        ),
        migrations.AddField(
            model_name='preprava',
            name='typ_vozidla',
            field=models.CharField(choices=[('SKL', 'Sklápěč'), ('WF', 'Walking Floor')], default='SKL', max_length=3),
        ),
    ]
