# Generated by Django 5.2.6 on 2025-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0005_remove_preprava_cena_pro_zakaznika_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprava',
            name='finalni_hmotnost_nakladka_kg',
        ),
        migrations.RemoveField(
            model_name='preprava',
            name='finalni_hmotnost_vykladka_kg',
        ),
        migrations.AddField(
            model_name='preprava',
            name='finalni_hmotnost_kg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Finální hmotnost (kg)'),
        ),
        migrations.AlterField(
            model_name='preprava',
            name='cena_za_tunu_zakaznik',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za tunu pro zákazníka'),
        ),
    ]
