# Generated by Django 5.2.6 on 2025-09-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0006_remove_preprava_finalni_hmotnost_nakladka_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprava',
            name='typ_vozidla',
            field=models.CharField(choices=[('SKL', 'Sklápěč'), ('WF', 'Walking Floor'), ('SKL_WF', 'Sklápěč/Walking Floor')], default='SKL', max_length=6),
        ),
    ]
