# Generated by Django 5.2.6 on 2025-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0007_alter_preprava_typ_vozidla'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='certifikace',
            field=models.TextField(blank=True, verbose_name='Certifikace'),
        ),
        migrations.AddField(
            model_name='partner',
            name='dalsi_kontakty',
            field=models.TextField(blank=True, verbose_name='Další kontakty (jméno, e-mail, tel.)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='fakturacni_udaje',
            field=models.TextField(blank=True, verbose_name='Fakturační údaje'),
        ),
        migrations.AddField(
            model_name='partner',
            name='typy_vozidel',
            field=models.TextField(blank=True, verbose_name='Typy vozidel'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='kontaktni_osoba',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontaktní osoba'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='typ_partnera',
            field=models.CharField(choices=[('zakaznik', 'Zákazník'), ('dopravce', 'Dopravce')], max_length=10, verbose_name='Typ partnera'),
        ),
    ]
