# Generated by Django 5.2.6 on 2025-09-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0008_partner_certifikace_partner_dalsi_kontakty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='splatnost_faktur_dny',
            field=models.IntegerField(blank=True, null=True, verbose_name='Splatnost faktur (dní)'),
        ),
    ]
