# Generated by Django 5.2.6 on 2025-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0009_partner_splatnost_faktur_dny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='typ_partnera',
            field=models.CharField(choices=[('zakaznik', 'Zákazník'), ('dopravce', 'Dopravce'), ('zakaznik_dopravce', 'Zákazník i dopravce')], max_length=20, verbose_name='Typ partnera'),
        ),
        migrations.AlterField(
            model_name='preprava',
            name='odhadovana_hmotnost_kg',
            field=models.IntegerField(default=24000, verbose_name='Odhadovaná hmotnost (kg)'),
        ),
    ]
