# Generated by Django 5.2.6 on 2025-09-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0010_alter_partner_typ_partnera_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokument',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partneři'},
        ),
        migrations.AlterModelOptions(
            name='preprava',
            options={'verbose_name': 'Přeprava', 'verbose_name_plural': 'Přepravy'},
        ),
        migrations.AddField(
            model_name='preprava',
            name='mena_dopravce',
            field=models.CharField(choices=[('CZK', 'Kč'), ('EUR', '€')], default='CZK', max_length=3, verbose_name='Měna (dopravce)'),
        ),
        migrations.AddField(
            model_name='preprava',
            name='mena_zakaznik',
            field=models.CharField(choices=[('CZK', 'Kč'), ('EUR', '€')], default='CZK', max_length=3, verbose_name='Měna (zákazník)'),
        ),
        migrations.AlterField(
            model_name='preprava',
            name='dopravce',
            field=models.ForeignKey(blank=True, limit_choices_to={'typ_partnera__in': ['dopravce', 'zakaznik_dopravce']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepravy_dopravce', to='logistika.partner'),
        ),
    ]
