# Generated by Django 5.2.6 on 2025-09-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0011_alter_dokument_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprava',
            name='zakaznik',
            field=models.ForeignKey(limit_choices_to={'typ_partnera__in': ['zakaznik', 'zakaznik_dopravce']}, on_delete=django.db.models.deletion.PROTECT, related_name='prepravy_zakaznik', to='logistika.partner'),
        ),
    ]
