# Generated by Django 5.2.6 on 2025-09-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0012_alter_preprava_zakaznik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprava',
            name='cena_za_tunu_zakaznik',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena za tunu pro zákazníka'),
        ),
    ]
