# Generated by Django 5.2.6 on 2025-09-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0013_alter_preprava_cena_za_tunu_zakaznik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprava',
            name='datum_cas_nakladky',
            field=models.CharField(max_length=50, verbose_name='Datum a čas nakládky'),
        ),
        migrations.AlterField(
            model_name='preprava',
            name='datum_cas_vykladky',
            field=models.CharField(max_length=50, verbose_name='Datum a čas vykládky'),
        ),
    ]
