# Generated by Django 4.2.24 on 2025-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0015_alter_partner_ic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('country_code', models.CharField(max_length=2)),
                ('regions', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Svatek',
                'verbose_name_plural': 'Svátky',
                'ordering': ['date', 'country_code', 'name'],
                'unique_together': {('date', 'country_code', 'name')},
            },
        ),
    ]
