# Generated by Django 4.2.24 on 2025-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0017_load_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprava',
            name='stav',
            field=models.CharField(choices=[('nova', 'Nová'), ('planovana', 'Plánovaná'), ('probiha', 'Probíhá'), ('dokoncena', 'Dokončená'), ('fakturace', 'K fakturaci'), ('uzavrena', 'Uzavřená'), ('neprodano', 'Neprodáno')], default='nova', max_length=20),
        ),
    ]
