# Generated by Django 4.2.24 on 2025-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0018_alter_preprava_stav'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprava',
            name='poznamka_final_hmotnost',
            field=models.CharField(blank=True, max_length=255, verbose_name='Poznámka k finální hmotnosti'),
        ),
        migrations.AddField(
            model_name='preprava',
            name='poznamka_odhad_hmotnost',
            field=models.CharField(blank=True, max_length=255, verbose_name='Poznámka k odhad. hmotnosti'),
        ),
    ]
