# Generated by Django 4.2.24 on 2025-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0019_preprava_poznamka_final_hmotnost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprava',
            name='odesilatel_cmr',
            field=models.TextField(blank=True, verbose_name='Odesílatel CMR'),
        ),
        migrations.AddField(
            model_name='preprava',
            name='prijemce_cmr',
            field=models.TextField(blank=True, verbose_name='Příjemce CMR'),
        ),
    ]
