# Generated by Django 4.2.24 on 2025-09-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika', '0020_preprava_odesilatel_cmr_preprava_prijemce_cmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprava',
            name='odhadovana_hmotnost_kg',
            field=models.IntegerField(default=25000, verbose_name='Odhadovaná hmotnost (kg)'),
        ),
        migrations.AlterField(
            model_name='preprava',
            name='typ_vozidla',
            field=models.CharField(choices=[('SKL', 'Sklápěč'), ('WF', 'Walking Floor'), ('SKL_WF', 'Sklápěč/Walking Floor')], default='SKL', max_length=10, verbose_name='Typ vozidla'),
        ),
    ]
